ItemNames:
	db "PLAGUE BARREL@"
	db "PLAGUE FLASK@"
	db "PLAGUE TUBE@"
	db "PLAGUE VIAL@"
	db "GPS@"
	db "PANDA FIRE@"
	db "?????@"
	db "SAFARI BALL@"
	db "POKéDEX@"
	db "AMETHYST@"
	db "KETAMINE@"
	db "CRUCIFIX@"
	db "NALOXONE@"
	db "A SLAP@"
	db "XANAX@"
	db "FULL RESTORE@"
	db "MORPHINE@"
	db "L S D@"
	db "ANTIBIOTICS@"
	db "PAINKILLERS@"
	db "20GAUGE SHELL@"
	db "XANAX BAR@"
	db "JACK BOTTLE@"
	db "SHAMROCK@"
	db "RED BANDANA@"
	db "WET PANTIES@"
	db "ROPE KNOT@"
	db "DARK CHIP@"
	db "ESCAPE ROPE@"
	db "MONOXIDE@"
	db "AGENT X@"
	db "SACRIFICE@"
	db "X-RAY@"
	db "BROKEN CONDOM@"
	db "HP UP@"
	db "PROTEIN@"
	db "IRON@"
	db "CARBOS@"
	db "MOTORBIKE@"
	db "AGENT P@"
	db "Z80-sn CHIP@"
	db "Z80-sp CHIP@"
	db "SECRET KEY@"
	db "?????@"
	db "GAS TANK@"
	db "X ACCURACY@"
	db "BAT GUANO@"
	db "CARD KEY@"
	db "KIDNEY@"
	db "PP UP@"
	db "VOODOO DOLL@"
	db "BE THE THING@"
	db "REVIVE@"
	db "FLAMETHROWER@"
	db "GUARD SPEC.@"
	db "CYANOGEN@"
	db "FLUORINE@"
	db "DIRE HIT@"
	db "COIN@"
	db "STEROIDS@"
	db "OUIJA BOARD@"
	db "LEMONADE@"
	db "TITANIC SEAT@"
	db "DARK CHIP@"
	db "SHIT@"
	db "DISKTOPIA@"
	db "X SPEED@"
	db "X SPECIAL@"
	db "AK 47@"
	db "25-I NBOME@"
	db "ITEMFINDER@"
	db "EMF SENSOR@"
	db "SHOVEL@"
	db "LIFT KEY@"
	db "EXP.ALL@"
	db "SPEAR@"
	db "HARPOON@"
	db "LANCE@"
	db "PP UP@"
	db "ETHER@"
	db "MAX ETHER@"
	db "ELIXER@"
	db "T N T@"
	db "B2F@"
	db "B1F@"
	db "1F@"
	db "2F@"
	db "3F@"
	db "4F@"
	db "5F@"
	db "6F@"
	db "7F@"
	db "8F@"
	db "9F@"
	db "10F@"
	db "11F@"
	db "B4F@"
