MoveNames::
	db "THUMP@"
	db "YING ZHUA@"
	db "DEASHI BARAI@"
	db "O UCHI GARI@"
	db "SUMI OTOSHI@"
	db "PAY DAY@"
	db "BLACK MASS@"
	db "METH HIT@"
	db "CHEMOTHERAPY@"
	db "SHANK UP@"
	db "MATA LEAO@"
	db "GUILLOTINE@"
	db "HURRICANE@"
	db "MAKE A SHIV@"
	db "CUT@"
	db "GUST@"
	db "WING ATTACK@"
	db "WHIRLWIND@"
	db "JET@"
	db "BIND@"
	db "SLAM@"
	db "COCAINE@"
	db "STOMP@"
	db "GEODEUP CHAGI@"
	db "BITURO CHAGI@"
	db "DOLLYO CHAGI@"
	db "DWI CHAGI@"
	db "SANDSTORM@"
	db "HEADBUTT@"
	db "RAPE@"
	db "GANG BANG@"
	db "ANAL RAPE@"
	db "TACKLE@"
	db "SODOMY@"
	db "BONDAGE@"
	db "ANAL GAPING@"
	db "THRASH@"
	db "DOUBLE-EDGE@"
	db "SHAKE BUTT@"
	db "DIRTY NEEDLE@"
	db "SYRINGE@"
	db "DRIVE-BY@"
	db "LEER@"
	db "BITE@"
	db "GROWL@"
	db "ROAR@"
	db "SING@"
	db "SUPERSONIC@"
	db "SONICBOOM@"
	db "DISABLE@"
	db "ACID@"
	db "RITUAL@"
	db "SABBATH@"
	db "MIST@"
	db "ACID PISS@"
	db "SQUIRT@"
	db "SURF@"
	db "ICE BEAM@"
	db "BLIZZARD@"
	db "PSYBEAM@"
	db "BUBBLEBEAM@"
	db "AURORA BEAM@"
	db "HYPER BEAM@"
	db "PECK@"
	db "DRILL PECK@"
	db "SUBMISSION@"
	db "LOW KICK@"
	db "COUNTER@"
	db "SEISMIC TOSS@"
	db "STRENGTH@"
	db "ABSORB@"
	db "METH HIT@"
	db "GROW CANNABIS@"
	db "GROWTH@"
	db "CUTTINGS@"
	db "OVERDOSE@"
	db "POISONPOWDER@"
	db "STUN SPORE@"
	db "GHB@"
	db "PARANOIA@"
	db "STRING SHOT@"
	db "GOD REVENGE@"
	db "SACRIFICE@"
	db "FAT MAN@"
	db "LITTLE BOY@"
	db "ELECTROCHAIR@"
	db "ELECTROCUTION@"
	db "LAPIDATION@"
	db "CONVULSION@"
	db "FISSURE@"
	db "DIG@"
	db "TOXIC@"
	db "CONFUSION@"
	db "MIND CONTROL@"
	db "HYPNOSIS@"
	db "MEDITATE@"
	db "AGILITY@"
	db "QUICK ATTACK@"
	db "RAGE@"
	db "TELEPORT@"
	db "STALKING@"
	db "MOCKINGBIRD@"
	db "SCREECH@"
	db "TSUKUYOMI@"
	db "REJUVENATE@"
	db "VIAGRA@"
	db "MINIMIZE@"
	db "SMOKESCREEN@"
	db "CONFUSE RAY@"
	db "COWARDICE@"
	db "DEFENSE CURL@"
	db "BARRIER@"
	db "LIGHT SCREEN@"
	db "HAZE@"
	db "REFLECT@"
	db "FOCUS ENERGY@"
	db "SADNESS@"
	db "METRONOME@"
	db "MIRROR MOVE@"
	db "SUICIDE@"
	db "EGG BOMB@"
	db "LICK@"
	db "SMOG@"
	db "SLUDGE@"
	db "BONE CLUB@"
	db "CHURCH BURN@"
	db "TSUNAMI@"
	db "CLAMP@"
	db "SHURIKEN@"
	db "SKULL BASH@"
	db "SPIKE CANNON@"
	db "CONSTRICT@"
	db "AMNESIA@"
	db "KINESIS@"
	db "PREGNANCY@"
	db "HI JUMP KICK@"
	db "GLARE@"
	db "DREAM EATER@"
	db "ZYKLON B@"
	db "BARRAGE@"
	db "LEECH LIFE@"
	db "JUDAH'S KISS@"
	db "SKY ATTACK@"
	db "TRANSFORM@"
	db "SPIT@"
	db "DIZZY PUNCH@"
	db "SPORE@"
	db "TORCH@"
	db "ALCOHOL@"
	db "SPLASH@"
	db "ACID ARMOR@"
	db "TOXIC WASTE@"
	db "KAMIKAZE@"
	db "FURY SWIPES@"
	db "BONEMERANG@"
	db "REST@"
	db "ROCK SLIDE@"
	db "HYPER FANG@"
	db "SHARPEN@"
	db "CONVERSION@"
	db "TRI ATTACK@"
	db "SUPER FANG@"
	db "SLASH@"
	db "DISCIPLE@"
	db "STRUGGLE@"
	db "PROTO CANNON@"
	db "MECHA PUNCH@"
	db "LOW ON MEMORY@"
	db "MACHINE LEARN@"
	db "CROP CIRCLES@"
	db "TIME WARP@"
	db "WRATH OF GOD@"
	db "JUDGEMENT@"

