TrainerNames:
	db "SKATER@"
	db "TRAP BOY@"
	db "RAPED GIRL@"
	db "TATTOOER@"
	db "PIG@"
	db "PIG@"
	db "SEX MANIAC@"
	db "CYBER SLAVE@"
	db "PIMP@"
	db "BIKER@"
	db "BURGLAR@"
	db "PYROMANIAC@"
	db "JUGGLER@"
	db "TERRORIST@"
	db "SEA SHITTER@"
	db "KKK MEMBER@"
	db "MAD GAMBLER@"
	db "BEAUTY@"
	db "PSYCHIC@"
	db "NICOLA PIRO@"
	db "JUGGLER@"
	db "TAMER@"
	db "XXXTENTACION@"
	db "BLACKBELT@"
	db "EVILIO@"
	db "THE PROF@"
	db "CHIEF@"
	db "SCIENTIST@"
	db "PLARIO@"
	db "PLAGUER@"
	db "COOLTRAINER♂@"
	db "COOLTRAINER♀@"
	db "BUDDHA@"
	db "KURT COBAIN@"
	db "LIL PEEP@"
	db "L. KILMISTER@"
	db "DOLORES@"
	db "TUPAC@"
	db "C.BENNINGTON@"
	db "A. WINEHOUSE@"
	db "KKK MEMBER@"
	db "EVILIO@"
	db "EVILIO@"
	db "JESUS CHRIST@"
	db "CULTIST@"
	db "MOHAMMED@"
	db "SATAN@"
